# MT4XAI Project Configuration
# Stores tunable parameters and empirically derived constants

project:
  random_seed: 42
  # root_dir is dynamically resolved automatically in config.py
  root_dir: null

paths:  
  # paths must be relative from project root
  # Data paths
  data_dir: "Data"
  dataset: "Data/etron55-charging-sessions.parquet"
  teaching_pool: "Data/teaching_pool"
  # Model paths
  models: "Models" 
  final_model: "Models/final/final_model.pth"
  # Other dir paths
  figures: "Figures"
  logs: "Logs"

inference:
  # final model hyperparams below derived from model tuning in notebook 3
  horizon: 5
  final_model_name: "final_model.pth"
  hidden_dim: 256
  num_layers: 4
  dropout: 0.0027575414563
  alpha_h: 0.5187590357622
  batch_size: 32
  grad_clip_norm: 5.0
  lr: 0.000501551534
  weight_decay: 0.0000011078448
  # values below derived from anomaly detection exploration in notebook 4
  horizon_decay_lambda: 0.4
  t_min_eval: 1  
  ad_rmse_threshold: 13.3423
  ad_pct_threshold: 95
  metric: "macro_rmse"

ors:
  # values derived from ORS exploration in notebook 5
  # power_stage1_mode: "dp_prefix"
  # power_dp_alpha: 
  # power_dp_q:
  # power_beta:
  # power_gamma: 
  # power_epsilon_value: 
  # power_R: 2000
  # power_min_k: 1
  # power_max_k: 12
  soc_stage1_mode: "rdp"  # None disables SOC channel entirely for inference, simplifications, plotting, teaching
  soc_rdp_epsilon: 0.75  # for RDP simplifications
  soc_rdp_candidates: 5
  soc_rdp_eps_min: 1.0e-6
  soc_rdp_eps_max: 100.0 
  stage2_err_metric: "l2"
  epsilon_mode: "fraction"

teaching:
  teaching_pool_dir: "../Data/teaching_pool"
  teaching_set_size: 60  # balanced across two classes: 10 + 10 for pre/post test, <=40 for teaching session
